require:
  - rubocop

included_files:
  - 'app/views/**/*.haml'

linters:
  Rubocop:
    enabled: true
    config_file: .rubocop.yml

  LineLength:
    enabled: false

  ViewLength:
    enabled: false
